#!/bin/bash

# macimage 项目初始化脚本
# 使用方法：在 Xcode 中创建新项目后，运行此脚本将源文件复制到项目中

echo "=== macimage 项目初始化 ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 打开 Xcode"
echo "2. 选择 'Create a new Xcode project'"
echo "3. 选择 'macOS' → 'App'"
echo "4. 设置："
echo "   - Product Name: macimage"
echo "   - Team: 你的开发者账号（或 None）"
echo "   - Organization Identifier: com.yourname"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "5. 保存到: /Users/cy/Documents/cola输出文件/mac看图小工具/"
echo ""
echo "创建项目后，将以下文件复制到项目中："
echo ""
echo "源文件（拖拽到 Xcode 项目的 macimage 文件夹）："
echo "  - macimageApp.swift"
echo "  - ContentView.swift"
echo "  - ImageViewer.swift"
echo "  - ToolbarView.swift"
echo "  - PageIndicator.swift"
echo "  - InfoOverlay.swift"
echo "  - ImageLoader.swift"
echo "  - HistoryManager.swift"
echo "  - Info.plist"
echo "  - Assets.xcassets"
echo ""
echo "或者，你可以直接在 Xcode 中："
echo "1. 删除自动生成的 ContentView.swift 和 macimageApp.swift"
echo "2. 将本目录下的所有 .swift 文件拖入项目"
echo "3. 确保 Info.plist 被添加到项目"
echo ""
echo "按任意键继续..."
read -n 1 -s

echo ""
echo "正在打开项目目录..."
open /Users/cy/Documents/claude输出文件/mac看图小工具/macimage
